### PR TITLE
suggestion only

### PR DESCRIPTION
**Pull request by vegarringdal**
DO NOT MERGE!
@devmondo @arjendeblok @nchanged 

Played around yesterday a little today on seed:
https://github.com/vegarringdal/fuse-box-aurelia-seed

What Ive done
* using the https://github.com/aurelia/skeleton-navigation/tree/master/skeleton-typescript
* removed the boostrap and query since they was not used, just bootstrap css
* added tslint (will just show errors in vscode, not fancy while building, hopefully some plugin will come for this)
* changed build to be in own folder to clean up root
* changed bundle to be in own folder to clean up root (also keeping)
* activated gh-pages, this is possible since Im keeping the bundle, and added [link] (https://vegarringdal.github.io/fuse-box-aurelia-seed/#/), I aslo added this to readme file #6
* added link to loader on readme
* renamed some variables so it says fusebox and shows the star

image

Edits on the readme file
image

### CODE REVIEW

**Comment by vegarringdal** [comment]
This was more or less a suggestion on some changes, its not perfect 😄  
@arjendeblok you have been great at making this sample app so fell it kinda should be up to you, if you want to use/take any of the suggestions etc 👍

**Comment by arjendeblok** [comment]
@vegarringdal I will take a look at it. I am now busy trying to get source mappings working for packages in the node_modules folder.

**Comment by vegarringdal** [comment]
@arjendeblok np, I got a workaround for my grid/aurelia plugins/modules on sourcemaps, but you will have to have own bundles for each one... so if its just one it should be ok during development

https://github.com/vegarringdal/aurelia-fusebox-test/blob/master/build/fb-aurelia-v-grid-build-bundle.js


image

**Comment by nchanged** [comment]
@vegarringdal why not merging? ) Awesome Job!

**Comment by vegarringdal** [comment]
> @vegarringdal why not merging? ) Awesome Job!

@nchanged good question, but very simple answer, no idea how to 😂 
I could merge all my bundles into one with ease ?

**Comment by vegarringdal** [comment]
@nchanged or are you talking about merging sample app and not bundles ? 😂

**Comment by nchanged** [comment]
i mean the PR....

**Comment by vegarringdal** [comment]
@nchanged hehe, ok

Well since @arjendeblok have pretty much made what we have now I did not want to be a ass and just merge my own PR because I can 👍 
For what I know @arjendeblok might have something cool going on, and might see some parts Im doing wrong/bad 😄

**Comment by devmondo** [comment]
this is awesome!!!

**Comment by arjendeblok** [comment]
@vegarringdal @nchanged let me get the best parts in my own PR and then decide what to do with the rest.

**Comment by vegarringdal** [comment]
@arjendeblok great, copy the parts you like and skip the other ones, like I said it was just a suggestion :-)

**Comment by arjendeblok** [comment]
@vegarringdal In your sample you removed bootstrap and jquery because it was not used. And you included a CDN for bootstrap CSS. 
I know it is not used in the sample but if people want to extend the code and use bootstrap JS parts then they would make a choice if to include bootstrap in the bundle together with JQuery (which requires a shim) or to get it also from the CDN. 
The samples for Aurelia also package bootstrap, so I copied this pattern. 
What is you opinion on this. Would you rather get it from a CDN or package it?

**Comment by arjendeblok** [comment]
You do you use [] in the build file for all JS, HTML and CSS files?
If you do that then you will have to include all imports in the JS files also in the build file as a dependency.
For example in my code I did not include fuse-box-aurelia-loader in the call to devServer, because it was imported/required in the main.ts file. But in your example you must also include in explicitly in the bundle.

**Comment by vegarringdal** [comment]
@arjendeblok 

>The samples for Aurelia also package bootstrap, so I copied this pattern.
What is you opinion on this. Would you rather get it from a CDN or package it?

We can keep the jquery and bootstrap to show that part, might be nice for others to use as sample.
But maybe we should add a comment for it then, that its just here to show how, not needed for sample.

> You do you use [] in the build file for all JS, HTML and CSS files?

Having it like you had works fine. :-)
Been playing a lot with many bundles/plugin package so Im just used to not let fusebox do to much magic :-) kinda liked when I knew what got included.


Take my PR as just a suggestion, use what you like and dump the rest :-)

**Comment by arjendeblok** [comment]
@vegarringdal  Created a PR that implements a lot of your suggestions. 
Please have a look at it.

**Pull request closed without merging**
