### PR TITLE
Initial version of seed based on aurelia/skeleton-navigation

### PR DESCRIPTION
**Pull request by arjendeblok**

### CODE REVIEW

**Comment by vegarringdal** [comment]
@arjendeblok 
Great, thanks for making this, doing ```npm install``` of a fork of your code atm 👍

**Comment by nchanged** [comment]
Wow! thanks a lot!

**Comment by nchanged** [comment]
Let's brush up the loader and release it.

**Comment by vegarringdal** [comment]
@arjendeblok 

**1:**
---
Just tried it, if you dont load the styles.css in the index.html the "loading screen" wont work

image

This should be:
image


**2:**
---
We should add a license

Official skeleton is, how does that affect us?
https://github.com/aurelia/skeleton-navigation/blob/master/LICENSE
image



**3:**
---
Would be great if it had sourcemaps :-)
I havent tried this my self yet, but think its easy to add


I see now that @nchanged already merged it :-)

**Comment by nchanged** [comment]
@vegarringdal yeah, just so exciting! Let's fix it all guys. We have not announced anything yet.

**Comment by vegarringdal** [comment]
@nchanged Hehe, had more minor stuff/suggestions, but saw you had merged already :-)

**Comment by vegarringdal** [comment]
Might as well just fork this one then :-)

@arjendeblok Will you do a PR on some fixes ? :-) Thanks for helping

**Comment by arjendeblok** [comment]
@vegarringdal I will do a PR on some fixes. No problem. Do you mean the 3 items you mentioned?

**Comment by vegarringdal** [comment]
@arjendeblok 
yes, created them as separate issues for now, so its easier to track 
Thank you. 👍

**Pull request merged**
